### PR TITLE
Add get_query_results to the Athena module

### PR DESCRIPTION
**Pull request by KhueNgocDang**
### Feature or Bugfix
- Feature

### Detail
- Add `get_query_results` function to the Athena module. This function returns the results of an Athena's QueryExecutionId as a Pandas DataFrame. It also works with UNLOAD and CTAS queries

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-4rfo0GHQ0u9a
* Commit ID: 914ce24b91d0ef03c728999fbfe7f15a708ec61b
* Result: SUCCEEDED
* [Build Logs](https://gqgcj9s2gc.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=26da0ceb-b19a-4392-96a5-255355f0a9ae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
Assigned for review. @KhueNgocDang thanks ! We will get to this in the beginning of the week.

**Review by jaidisido — APPROVED** [review]
LGTM

**Review by malachi-constant — APPROVED** [review]
@KhueNgocDang Thanks for the contribution, approved.

**Pull request merged**
