### PR TITLE
Update pyarrow

### PR DESCRIPTION
**Pull request by maxispeicher**
*Issue #557 :*

*Description of changes:*
Accepting `pyarrow==4.0.0`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jaidisido** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-sDRE8Pq0duHT
* Commit ID: b2339a070ccb198db80b1accf613f8f2037324f2
* Result: SUCCEEDED
* [Build Logs](https://ozufyid077.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=39c80f9c-ccbd-41ca-9090-3b23db806a61%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by jaidisido** [comment]
Thanks @maxispeicher, we need to check on our side if building the Lambda layer with the 4.0.0 arrow branch (instead of [3.0.0](https://github.com/awslabs/aws-data-wrangler/blob/1d40edf9a09d41957f675878039752f13f0fbe88/building/lambda/build-lambda-layer.sh#L17)) does not lead to issues. At least none of the tests broke 👍🏼

**Comment by maxispeicher** [comment]
@jaidisido If I can help you with it, just let me know 🙂

**Comment by jaidisido** [comment]
I have tested the wheel and lambda layer builds and did not encounter issues, so all good!

**Pull request merged**
