### PR TITLE
Enable s3.to_parquet to recieve "zstd" compression type 

### PR DESCRIPTION
**Pull request by takeknock**
### Feature or Bugfix
- Feature

### Detail
- Enable s3.to_parquet to recieve "zstd" as compression type.

### Relates
- Nothing

### CODE REVIEW

**Comment by takeknock** [comment]
@kukushking Colud you approve running workflows as mainttainer? If there is any person with this problmme.(I have fixed mypy error)

**Comment by malachi-constant** [comment]
@takeknock I've reverted the `mypy` version used in our static checks that forced you to add this [commit](https://github.com/awslabs/aws-data-wrangler/pull/1369/commits/d540098c9b857cbf07a33ae212b611dbd0f3ffa9) . You should be ok to revert that and rerun now.

**Comment by takeknock** [comment]
@malachi-constant Thank you for your support and kind instruction. I've also revert needless [commit](https://github.com/awslabs/aws-data-wrangler/pull/1369/commits/d540098c9b857cbf07a33ae212b611dbd0f3ffa9) which is for only mypy 0.960. 
I've run ./validate.sh and confirmed that code pass validate.sh check.

**Comment by malachi-constant** [comment]
> @malachi-constant Thank you for your support and kind instruction. I've also revert needless [commit](https://github.com/awslabs/aws-data-wrangler/pull/1369/commits/d540098c9b857cbf07a33ae212b611dbd0f3ffa9) which is for only mypy 0.960. I've run ./validate.sh and confirmed that code pass validate.sh check.

Of course ! Thanks for you contribution. Looks like checks are passing. I'm going to add some reviewers on this PR and they will get to it soon. Most of the team is on holiday this week.

**Review by jaidisido — APPROVED** [review]

**Comment by jaidisido** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubCodeBuild8756EF16-pDO66x4b9gEu
* Commit ID: e92fe8c72036dc8f9198258067d59976d80cf8a1
* Result: SUCCEEDED
* [Build Logs](https://8z22lm66x0.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=825be032-68d0-49b7-bdcd-46bc8ca92299%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
