### PR TITLE
refact: Breaking Change - Modify named params style in Athena formatter

### PR DESCRIPTION
**Pull request by jaidisido**
### Feature or Bugfix
- Refactoring

### Detail
Modifying named parameters style in Athena queries so it follows PEP 0249 convention

https://peps.python.org/pep-0249/#paramstyle

As a result user must pass `:name` instead of `:name;`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubDistributedCodeBuild6-jWcl5DLmvupS
* Commit ID: 61f7b829b8f59be81c5c032688c96a2e6b1ac617
* Result: SUCCEEDED
* [Build Logs](https://p0rshq9q5i.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=aaa1dce3-43b0-4bcf-b35e-2314d0ea5b6c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubLoadTests5656BB24-s6u9F3qN9oFy
* Commit ID: 61f7b829b8f59be81c5c032688c96a2e6b1ac617
* Result: FAILED
* [Build Logs](https://pciyom2pbh.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3bde9436-64f2-4287-a6d7-4627773ca657%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by malachi-constant** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: GitHubStandardCodeBuild8C06-llutOAimTATs
* Commit ID: 61f7b829b8f59be81c5c032688c96a2e6b1ac617
* Result: SUCCEEDED
* [Build Logs](https://jsv9u8gote.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a9f69ffa-19ea-4d33-9ac8-2406274d195f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by LeonLuttenberger** [comment]
@jaidisido What happens if there are two parameters where one is a prefix of the other?

So we have `:date` and `:date2`. When the caller provides parameter values for `date` and `date2`, `date` will replace both of the parameters in the query, except the latter will be suffixed by `2`. We need to make sure we are only replacing full tokens.

**Pull request merged**
