### PR TITLE
Generate html doc for notebooks

### PR DESCRIPTION
**Pull request by maxispeicher**
*Issue #551:*

*Description of changes:* Convert Jupyter Notebooks to HTML during documentation build for a static version of the tutorials with the help of `nbsphinx` and `nbsphinx-link`.
Right now the links in the docstrings point to `2.4.0-docs` where the tutorial notebooks do not exist right now, but with the next release and a substitution of `2.4.0-docs` to `2.5.0-docs` everything should be linked just fine (a little chicken egg problem).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by igorborgest — APPROVED** [review]
Looks great!

**Comment by igorborgest** [comment]
is it ready, right?

**Comment by maxispeicher** [comment]
Yes 👍

**Comment by igorborgest** [comment]
It is already available on the "latest" and will be move to "stable" in the next release!

**Pull request merged**
