### PR TITLE
Upload/download files to/from S3

### PR DESCRIPTION
**Pull request by danielwo**
*Issue #, if available:*
#506 

*Description of changes:*
Add functionality to upload and download files to/from S3.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by danielwo** [comment]
Some thoughts: 

- Boto3 allows uploading either a file, or a file-like object and has two functions: upload_file and upload_fileobj. Should these be separated out here into upload_file and upload_fileobj, or is do you think this is fine?
- I left `s3_additional_kwargs` alone to be consistent with other functions, however, as there are no pandas_kwargs, this could be just **s3_additional_kwargs.

**Comment by danielwo** [comment]
An additional functionality that might be useful: when uploading/downloading, if only folder is specified, use same key. This does really overload the `local_file` param however.

e.g. `wr.s3.download(path='s3://bucket/key', local_file='./')` should download file to `./key`.

**Review by igorborgest — APPROVED** [review]
Seems great! Thanks for adding tests and update the tutorial.

**Comment by igorborgest** [comment]
@danielwo if the PR is ready, please convert it from draft to a regular PR and let's merge it 🙂

**Pull request merged**
